### ISSUE TITLE
Any info on the build

### ISSUE THREAD

**Issue by mattgrogan** [hmallen/squirrel-zapper#1]
Hey any info on how you built this? I'm looking to do something similar. Did it work?

**Comment by hmallen** [comment]
Unfortunately life got in the way, and it never got to a prototype stage. I did disassemble one of those electric tennis racket fly swatters and start to reverse engineer the circuit. It's essentially a couple voltage multipliers that boost voltage up to a point where you'll get an arc. You can also try electric bbq grill ignitor or something similar and trigger it using something to switch voltage to the device like a relay or mosfet. As you might have seen in the code, I planned on using the nRF01+ as a remote control, then control the switch with one of the Arduino's digital outputs.

**Comment by mattgrogan** [comment]
ok cool thanks for the reply.
